In [53]:
import torch
from torch.utils.data import Dataset as Dataset

In [65]:
tl1 = [torch.tensor(i) for i in range(10)]
tl2 = [torch.tensor(i*2) for i in range(10)]

In [60]:
class SimpleDataSet(Dataset):
    def __init__(self, data, targets):
        super(SimpleDataSet, self).__init__()
        assert data.shape[0] == targets.shape[0] # assuming shape[0] = dataset size
        self.data = data
        self.targets = targets

    def __len__(self):
        return self.targets.shape[0]

    def __getitem__(self, index):
        return self.data[index], self.targets[index].item()

In [77]:
tds = SimpleDataSet(torch.stack(tl1), torch.stack(tl2))

In [81]:
(tds.targets % 3 == 0).nonzero().reshape(-1)

tensor([0, 3, 6, 9])

In [94]:
tds3ix = (tds.targets % 3 == 0).nonzero().reshape(-1)
td_loader = torch.utils.data.DataLoader(dataset=tds, batch_size=len(tds3ix), sampler=torch.utils.data.SubsetRandomSampler(tds3ix))


In [130]:
torch.tensor([1], dtype=torch.int)

tensor([1], dtype=torch.int32)

In [119]:
torch.manual_seed(1)

In [120]:
for i in range(5):
    print(next(iter(td_loader)))

[tensor([0, 9, 3, 6]), tensor([ 0, 18,  6, 12])]
[tensor([3, 9, 6, 0]), tensor([ 6, 18, 12,  0])]
[tensor([0, 9, 3, 6]), tensor([ 0, 18,  6, 12])]
[tensor([3, 9, 6, 0]), tensor([ 6, 18, 12,  0])]
[tensor([6, 0, 9, 3]), tensor([12,  0, 18,  6])]


In [98]:
device = torch.device('cpu')

x = torch.tensor([[1,2,3],[4,5,6],[7,8,9]], dtype=torch.float)
y = torch.tensor([[ 2.8191,  4.3610,  3.7487],
        [ 3.8279, 12.9571, 10.9117],
        [ 4.8367, 21.5532, 18.0747]])

w1 = torch.randn(3, 1, device=device, requires_grad=True)
w2 = torch.randn(3, 1, device=device, requires_grad=True)
w3 = torch.randn(3, 1, device=device, requires_grad=True)
w = torch.stack((w1, w2, w3))
# w.squeeze_(-1)
print(w)

tensor([[[ 0.8590],
         [ 0.7056],
         [-0.3406]],

        [[-1.2720],
         [-1.1948],
         [ 0.0250]],

        [[-0.7627],
         [ 1.3969],
         [-0.3245]]], grad_fn=<StackBackward0>)


In [38]:
dw = torch.detach(w).clone()

In [42]:
dw[1].requires_grad

True

In [151]:
import sys

class NullStream:
        @staticmethod
        def write(*_): pass
        @staticmethod
        def flush(*_): pass

def print_to_stdout_and_stream(stream, text):
        sys.stdout.write(text)
        sys.stdout.flush()
        stream.write(text)
        stream.flush()
        
print_to_stdout_and_stream(NullStream, "blabla")
print_to_stdout_and_stream(NullStream, "blabla")

blablablabla

In [177]:
import datetime

print(datetime.datetime.utcnow().strftime("%Y-%m-%d-%H-%M-%S"))

2023-03-08-08-49-18


In [157]:
del(a)
for i in range(2):
    a=20

print(a)

20


In [ ]:
learning_rate = 1e-5
for t in range(50):
  y_pred = x.mm(w)
  loss = (y_pred - y).pow(2).sum()
  if t%5000==0:
    print(t, loss.item())
  loss.backward()